

<h3>Danh sách loại công việc</h3>
<hr />

<?php
// Số lượng dữ liệu trên mỗi trang
$itemsPerPage = 6;

// Tính tổng số trang
$totalPages = ceil(count($data) / $itemsPerPage);

// Trang hiện tại (mặc định là trang 1 nếu không có trang nào được chọn)
$current_page = isset($_GET['page']) ? $_GET['page'] : 1;

// Tính chỉ mục bắt đầu và kết thúc của dữ liệu cho trang hiện tại
$startIndex = ($current_page - 1) * $itemsPerPage;
$endIndex = min($startIndex + $itemsPerPage - 1, count($data) - 1);
?>


<table class="table table-striped table-hover align-middle">
    <thead>
        <tr>
            <th scope="col" style="width: 5%">#</th>
            <th scope="col" style="width: 20%">Mã Loại Công Việc</th>
            <th scope="col" style="width: 45%">Tên Loại Công Việc</th>
            <th scope="col" style="width: 20%">Ngày tạo</th>
            <th scope="col" style="width: 10%"></th>
        </tr>
    </thead>
    <tbody>
        <?php for ($i = $startIndex; $i <= $endIndex; $i++) : ?>
            <tr>
                <th scope="row"><?php echo $i + 1; ?></th>
                <td ><?php echo $data[$i]->id; ?></td>
                <td><?php echo $data[$i]->name; ?></td>
                <td ><?php echo $data[$i]->date_created; ?></td>       
                <td>
                    <a class="btn btn-outline-danger" href="index.php?action=delete_cate&id=<?php echo $data[$i]->id; ?>" role="button">Xóa</a>
                </td>        
            </tr>
        <?php endfor; ?>
    </tbody>
</table>
<a class="btn btn-outline-success" href="index.php?action=add_cate" role="button"> + Thêm mới loại công việc</a>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-end">
    <li class="page-item">
      <a class="page-link" href="index.php?action=cate_list&page=1" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <?php for ($page = 1; $page <= $totalPages; $page++) : ?>
        <li class="page-item<?php echo ($current_page == $page) ? ' active' : ''; ?>">
            <a class="page-link" href="index.php?action=cate_list&page=<?php echo $page; ?>"><?php echo $page; ?></a>
        </li>
    <?php endfor; ?>
      <a class="page-link" href="index.php?action=cate_list&page=<?php echo $totalPages; ?>" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>
<?php
    if (isset($res) && $res != "") {
        echo $res;
    }
    ?>
