
<h1>MY TODO LIST</h1>
<hr/>

<div class="d-grid gap-2 col-6 mx-auto">
<a class="btn btn-outline-success" href="index.php?action=add_task" role="button">Thêm mới công việc</a>
<a class="btn btn-outline-success" href="index.php?action=task_list" role="button">Xem danh sách công việc</a>
<a class="btn btn-outline-success" href="index.php?action=cate_list" role="button">Xem danh sách loại công việc</a>

<?php
$x = 3.2;
$$x = "b";
$$$x = "c";
$y = 3;

echo "$b <br/>";
echo "$$x <br/>";
echo "${$x} <br/>";

echo $x + $y;
?>
</div>
